### Illumina specific
DATABASE    PhiX        /fastq_screen/fastqs_databases/phix/genome
DATABASE    Adapters    /fastq_screen/fastqs_databases/adapters/seq_adapters

### High abundance 
DATABASE    rnammer     /fastq_screen/fastqs_databases/rnammer/rnammer-1.2
DATABASE    H_rRNA      /fastq_screen/fastqs_databases/h_rrna/human_rRNA
DATABASE    H_tRNA      /fastq_screen/fastqs_databases/h_trna/hg38-tRNAs
DATABASE    H_MT        /fastq_screen/fastqs_databases/h_mt/chrM

### Lab Contamination
DATABASE    UniVec_Core     /fastq_screen/fastqs_databases/univec_core/UniVec_Core
DATABASE    Yeast           /fastq_screen/fastqs_databases/yeast/genome
